//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toletBDdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ad()
        {
            this.Interesteds = new HashSet<Interested>();
        }
    
        public string users_id { get; set; }
        public string phone { get; set; }
        public string rent { get; set; }
        public byte[] img1 { get; set; }
        public byte[] img2 { get; set; }
        public byte[] img3 { get; set; }
        public byte[] img4 { get; set; }
        public Nullable<System.DateTime> datee { get; set; }
        public string availability { get; set; }
        public string city { get; set; }
        public string area { get; set; }
        public string street_name { get; set; }
        public string street_no { get; set; }
        public string additional_addresss { get; set; }
        public string number_of_room { get; set; }
        public string number_of_kitchen { get; set; }
        public string number_of_bathroom { get; set; }
        public string size_of_flat { get; set; }
        public string additional_info { get; set; }
        public string ad_id { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interested> Interesteds { get; set; }
    }
}
