//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toletBDdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresss
    {
        public string city { get; set; }
        public string area { get; set; }
        public string street_name { get; set; }
        public string street_no { get; set; }
        public string additional_addresss { get; set; }
        public int addresss_id { get; set; }
    }
}
