//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toletBDdb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class toletBDdbEntities1 : DbContext
    {
        public toletBDdbEntities1()
            : base("name=toletBDdbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ad> Ads { get; set; }
        public virtual DbSet<Addresss> Addressses { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Detailsofad> Detailsofads { get; set; }
        public virtual DbSet<Govern> Governs { get; set; }
        public virtual DbSet<Interested> Interesteds { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
